name: Download and Release APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-apks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependecies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget curl ca-certificates gnupg
        sudo apt-get install -y unzip tar

    - name: Download and extract curl-impersonate
      run: |
        VERSION="v0.6.1.x86_64-linux-gnu"
        VERSIONSHORT="v0.6.1"

        wget https://github.com/lwthiker/curl-impersonate/releases/download/$VERSIONSHORT/curl-impersonate-$VERSION.tar.gz
        tar -xzf curl-impersonate-$VERSION.tar.gz
        ls -R curl-impersonate-$VERSION/
        sudo mv curl-impersonate-$VERSION/* /usr/local/bin/

    - name: Download the XAPK file
      run: |
        curl_chrome116 -L -o downloaded_file.xapk "https://d.apkpure.com/b/XAPK/com.roblox.client?version=latest" --cacert /etc/ssl/certs/ca-bundle.crt

    - name: Unpack the downloaded file
      run: |
        mkdir unpacked
        unzip downloaded_file.xapk -d unpacked

    - name: Find APK files
      id: find_apks
      run: |
        apk_files=$(find unpacked -type f -name "*.apk")
        echo "APK_FILES=$apk_files" >> $GITHUB_ENV

    - name: Create a GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false

    - name: Upload APK files
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.APK_FILES }}
        asset_name: $(basename ${{ env.APK_FILES }})
        asset_content_type: application/vnd.android.package-archive
