name: Download and Release APKs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release-apks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Download the XAPK file
      run: |
        curl -L -o downloaded_file.xapk "https://d.apkpure.com/b/XAPK/com.roblox.client?version=latest"
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip
      
    - name: Unpack the downloaded file
      run: |
        mkdir unpacked
        unzip downloaded_file.xapk -d unpacked
      
    - name: Find APK files
      id: find_apks
      run: |
        apk_files=$(find unpacked -type f -name "*.apk")
        echo "APK_FILES=$apk_files" >> $GITHUB_ENV
      
    - name: Create a GitHub release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.0
        release_name: Release v1.0.0
        draft: false
        prerelease: false
      
    - name: Upload APK files
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ env.APK_FILES }}
        asset_name: $(basename ${{ env.APK_FILES }})
        asset_content_type: application/vnd.android.package-archive
